---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"
  environments_path: test/environments
  solo_rb:
    environment: kitchen

platforms:
  - name: centos-7.1
  - name: centos-6.6
  - name: centos-6.5
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[symfony::default]
    attributes:
